### ISSUE TITLE
Error Installing on Windows Server 2016

### ISSUE THREAD

**Issue by nungster** [ptarmiganlabs/butler-cw#5]
I am trying to install butler-cw on a Windows 2016 server and Qlik Sense June 2018.  The Qix engine is 12.120.7 (edited js file accordingly).  When I go to run it, I get:
C:\butler-cw-master>node index.js
2018-08-31T23:22:48.919Z - info: Starting Qlik Sense cache warmer.
module.js:478
    throw err;
    ^

Error: Cannot find module 'enigma.js/schemas/qix/12.170.2/schema.json'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\butler-cw-master\index.js:45:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

**Comment by mountaindude** [comment]
Yup, you got it right. 
We need to bump Enigma.js version to latest. I've accepted your PR and will do a general refresh of the code base. Will also create the needed files to run Butler CW as a Docker container - this greatly simplifies installation and operation.

**Comment by nungster** [comment]
Awesome!  Thanks!  Docker would be super awesome as well!
